# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage:Build
  jobs:
  - job: Job Build
    steps:
    - bash: echo Hello, world!
  - job:Job Build mark
    dependsOn: Job Build
    steps:
    - bash: echo Build mark

- stage:devDeploy
  jobs:
    - job: Job devDeploy
      steps:
      - bash: echo stage devDeploy
      
- stage:prodDeploy
  jobs:
      - job: prodDeploy
        steps:
        - bash: echo stage prodDeploy
